services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: login_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: yourpassword
      DB_NAME: login_db

  selenium:
    image: selenium/standalone-chrome:125.0
    shm_size: 2gb # prevents Chrome from choking on /dev/shm
    ports:
      - "4444:4444" # WebDriver endpoint
volumes:
  db_data:
